"""
Smoke tests for hybrid retriever.

Run: pytest apps/mas/rag/tests/test_retriever.py -v
"""

from __future__ import annotations

import tempfile
import pytest
import numpy as np


class MockEmbedder:
    """Mock embedder for testing without API calls."""
    
    dimension = 1536
    
    def __init__(self):
        # Use fixed seed for reproducibility
        self.rng = np.random.RandomState(42)
    
    def embed_documents(self, texts):
        """Return deterministic vectors based on text hash."""
        vecs = []
        for text in texts:
            # Use text hash to generate reproducible vector
            seed = hash(text) % (2**31)
            rng = np.random.RandomState(seed)
            vecs.append(rng.rand(1536).astype('float32'))
        return np.array(vecs)
    
    def embed_query(self, query):
        """Return deterministic vector based on query hash."""
        seed = hash(query) % (2**31)
        rng = np.random.RandomState(seed)
        return rng.rand(1536).astype('float32')


@pytest.fixture
def populated_db():
    """Create and populate a test database."""
    from apps.mas.rag.indexer import WikipediaIndexer
    
    with tempfile.TemporaryDirectory() as tmpdir:
        embedder = MockEmbedder()
        indexer = WikipediaIndexer(tmpdir, embedder)
        
        # Create diverse test documents
        docs = [
            {
                "id": "math_1",
                "title": "Cayley Graphs",
                "text": "A Cayley graph is a graph that encodes the abstract structure of a group. "
                       "It is constructed using a group G and a generating set S. "
                       "The eigenvalues of Cayley graphs can be computed using character theory.",
                "url": "http://wiki/cayley"
            },
            {
                "id": "math_2",
                "title": "Eigenvalue Computation",
                "text": "Eigenvalues are scalar values associated with linear transformations. "
                       "For a matrix A, the eigenvalues satisfy det(A - λI) = 0. "
                       "In spectral graph theory, eigenvalues reveal structural properties.",
                "url": "http://wiki/eigenvalue"
            },
            {
                "id": "knot_1",
                "title": "Knot Theory",
                "text": "Knot theory studies mathematical knots. A knot is an embedding of a circle "
                       "in 3D space. The figure-8 knot is an important example. "
                       "Quandles are algebraic structures used to distinguish knots.",
                "url": "http://wiki/knot"
            },
            {
                "id": "group_1",
                "title": "Group Theory Basics",
                "text": "A group is a set with an associative binary operation, identity, and inverses. "
                       "Abelian groups are commutative. Cyclic groups are generated by a single element. "
                       "Subgroups are subsets that form groups themselves.",
                "url": "http://wiki/group"
            },
            {
                "id": "misc_1",
                "title": "Cooking Recipes",
                "text": "Pasta is made from wheat flour and water. Italian cuisine features many pasta dishes. "
                       "Tomato sauce is a common accompaniment. Pizza is another popular Italian dish.",
                "url": "http://wiki/cooking"
            },
        ]
        
        indexer.index_documents(docs, chunk_size=300, show_progress=False)
        
        yield tmpdir, embedder


class TestHybridRetriever:
    """Tests for the hybrid retriever."""
    
    def test_semantic_search_returns_results(self, populated_db):
        """Verify semantic search returns ranked results."""
        from apps.mas.rag.retriever import HybridRetriever
        
        db_path, embedder = populated_db
        retriever = HybridRetriever(db_path=db_path, embedder=embedder)
        
        results = retriever.semantic_search("eigenvalue computation", k=5)
        
        assert len(results) > 0
        assert all(isinstance(r, tuple) and len(r) == 2 for r in results)
        # Results should be (id, distance) tuples
        for doc_id, distance in results:
            assert isinstance(doc_id, str)
            assert isinstance(distance, (int, float))
    
    def test_lexical_search_returns_results(self, populated_db):
        """Verify lexical/BM25 search returns ranked results."""
        from apps.mas.rag.retriever import HybridRetriever
        
        db_path, embedder = populated_db
        retriever = HybridRetriever(db_path=db_path, embedder=embedder)
        
        results = retriever.lexical_search("Cayley graph", k=5)
        
        assert len(results) > 0
    
    def test_fusion_search_returns_chunks(self, populated_db):
        """Verify RRF fusion returns RetrievedChunk objects."""
        from apps.mas.rag.retriever import HybridRetriever
        
        db_path, embedder = populated_db
        retriever = HybridRetriever(db_path=db_path, embedder=embedder)
        
        results = retriever.fusion_search("matrix eigenvalue", k=5)
        
        assert len(results) <= 5
        for chunk in results:
            assert hasattr(chunk, 'text')
            assert hasattr(chunk, 'title')
            assert hasattr(chunk, 'score')
            assert hasattr(chunk, 'retrieval_method')
    
    def test_fusion_search_empty_query(self, populated_db):
        """Verify empty query returns empty results."""
        from apps.mas.rag.retriever import HybridRetriever
        
        db_path, embedder = populated_db
        retriever = HybridRetriever(db_path=db_path, embedder=embedder)
        
        results = retriever.fusion_search("", k=5)
        assert results == []
    
    def test_search_unified_interface(self, populated_db):
        """Verify unified search interface works for all methods."""
        from apps.mas.rag.retriever import HybridRetriever
        
        db_path, embedder = populated_db
        retriever = HybridRetriever(db_path=db_path, embedder=embedder)
        
        query = "group theory"
        
        # Test all methods
        for method in ["semantic", "lexical", "fusion"]:
            results = retriever.search(query, k=3, method=method)
            assert isinstance(results, list)
    
    def test_format_context(self, populated_db):
        """Verify context formatting works."""
        from apps.mas.rag.retriever import HybridRetriever
        
        db_path, embedder = populated_db
        retriever = HybridRetriever(db_path=db_path, embedder=embedder)
        
        chunks = retriever.fusion_search("knot theory", k=3)
        context = retriever.format_context(chunks, max_length=1000)
        
        assert isinstance(context, str)
        assert len(context) <= 1000
        if chunks:
            assert "[1]" in context  # Should have numbered entries
    
    def test_rrf_parameters(self, populated_db):
        """Verify RRF parameters affect results."""
        from apps.mas.rag.retriever import HybridRetriever
        
        db_path, embedder = populated_db
        
        # High semantic weight
        retriever_semantic = HybridRetriever(
            db_path=db_path,
            embedder=embedder,
            semantic_weight=0.9,
            lexical_weight=0.1,
        )
        
        # High lexical weight
        retriever_lexical = HybridRetriever(
            db_path=db_path,
            embedder=embedder,
            semantic_weight=0.1,
            lexical_weight=0.9,
        )
        
        # Both should return results
        results_sem = retriever_semantic.fusion_search("eigenvalue", k=3)
        results_lex = retriever_lexical.fusion_search("eigenvalue", k=3)
        
        assert len(results_sem) > 0
        assert len(results_lex) > 0

